"""initial migrations

Revision ID: 9c9ea4b0ad01
Revises: 
Create Date: 2024-05-21 16:14:13.034268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9ea4b0ad01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('odd_home', sa.String(), nullable=True),
    sa.Column('out', sa.String(), nullable=True),
    sa.Column('odd_out', sa.String(), nullable=True),
    sa.Column('tie', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogos')
    # ### end Alembic commands ###
